# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalysisWindow123.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
from PyQt5.QtCore import QDir, Qt
from PyQt5.QtWidgets import QMessageBox
from Functions.FMImplementation import *



class Ui_AnalysisWindow(object):

    def openMainWindow(self):
        from MainWindow import Ui_MainWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, AnalysisWindow):
        self.w = 634
        self.h = 519
        AnalysisWindow.setObjectName("AnalysisWindow")
        AnalysisWindow.resize(self.w, self.h)
        AnalysisWindow.setFixedSize(self.w, self.h)
        AnalysisWindow.setStyleSheet('background-color:black;')
        self.centralwidget = QtWidgets.QWidget(AnalysisWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(self.w//2 - 30//2 + 24, 180, 30, 21))
        self.label5.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Microsoft Uighur")
        font.setPointSize(14)
        self.label5.setFont(font)
        self.label5.setStyleSheet("color: white;")
        self.label5.setObjectName("label5")
        self.label6 = QtWidgets.QLabel(self.centralwidget)
        self.label6.setGeometry(QtCore.QRect(40, 240, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Uighur")
        font.setPointSize(14)
        self.label6.setFont(font)
        self.label6.setStyleSheet("color: white;")
        self.label6.setObjectName("label6")
        self.textEdit5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit5.setGeometry(QtCore.QRect(290, 240, 181, 21))
        self.textEdit5.setStyleSheet("color: white;")
        self.textEdit5.setObjectName("textEdit5")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(0, 70, self.w, 20))
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Microsoft Uighur")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setStyleSheet("color: white;")
        self.label3.setObjectName("label3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(25, 180, 60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft Uighur")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.CorrectButton = QtWidgets.QPushButton(self.centralwidget)
        self.CorrectButton.setGeometry(QtCore.QRect(self.w//2 - 141//2, 290, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Uighur")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.CorrectButton.setFont(font)
        self.CorrectButton.setStyleSheet("background:blue;\n"
"border-color: rgb(4, 111, 2);\n"
"border-radius:10px;\n"
"font: bold 18px;\n"
"padding: 6px;\n"
"border-style: outset;\n"
"border-width: 0.3px;\n"
"border-color: rgb(0, 0, 127);\n"
"color: white;\n"
"\n"
"")
        self.CorrectButton.setObjectName("CorrectButton")
        self.textEdit3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit3.setGeometry(QtCore.QRect(self.w//2 - self.w//4 - 231//2 + 45, 170, 231, 51))
        self.textEdit3.setStyleSheet("color: white;")
        self.textEdit3.setObjectName("textEdit3")
        self.heading = QtWidgets.QLabel(self.centralwidget)
        self.heading.setGeometry(QtCore.QRect(0, 10, self.w, 45))
        self.heading.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(18)
        self.heading.setFont(font)
        self.heading.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.heading.setAutoFillBackground(False)
        self.heading.setStyleSheet("color: white;")
        self.heading.setObjectName("heading")
        self.textEdit4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit4.setGeometry(QtCore.QRect(self.w//2 + self.w//4 - 231//2 + 5, 170, 231, 51))
        self.textEdit4.setStyleSheet("color: white;")
        self.textEdit4.setObjectName("textEdit4")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(self.w//2 - 521//2, 320, 521, 71))
        self.textEdit.setStyleSheet("color: white;")
        self.textEdit.setObjectName("textEdit")
        self.GoBack = QtWidgets.QPushButton(self.centralwidget)
        self.GoBack.setGeometry(QtCore.QRect(40, 420, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Microsoft Uighur")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.GoBack.setFont(font)
        self.GoBack.setStyleSheet("background:blue;\n"
"border-color: rgb(4, 111, 2);\n"
"border-radius:10px;\n"
"font: bold 18px;\n"
"padding: 6px;\n"
"border-style: outset;\n"
"border-width: 0.3px;\n"
"border-color: rgb(0, 0, 127);\n"
"color: white;\n"
"\n"
"")
        self.GoBack.setObjectName("GoBack")
        self.DataSetButton = QtWidgets.QPushButton(self.centralwidget)
        self.DataSetButton.setGeometry(QtCore.QRect(40, 120, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Uighur")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.DataSetButton.setFont(font)
        self.DataSetButton.setStyleSheet("background:blue;\n"
"border-color: rgb(4, 111, 2);\n"
"border-radius:10px;\n"
"font: bold 18px;\n"
"padding: 6px;\n"
"border-style: outset;\n"
"border-width: 0.3px;\n"
"border-color: rgb(0, 0, 127);\n"
"color: white;\n"
"\n"
"\n"
"")
        self.DataSetButton.setObjectName("DataSetButton")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(160, 120, 241, 21))
        self.textEdit_2.setStyleSheet("color: white;")
        self.textEdit_2.setObjectName("textEdit_2")
        AnalysisWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AnalysisWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, self.w, 21))
        self.menubar.setObjectName("menubar")
        AnalysisWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnalysisWindow)
        self.statusbar.setObjectName("statusbar")
        AnalysisWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AnalysisWindow)
        QtCore.QMetaObject.connectSlotsByName(AnalysisWindow)

        self.textEdit_2.setDisabled(True)
        #connect button to function
        self.CorrectButton.clicked.connect(self.al)
        self.GoBack.clicked.connect(self.openMainWindow)
        self.GoBack.clicked.connect(AnalysisWindow.close)
        self.DataSetButton.clicked.connect(self.openDialogBox)

    def retranslateUi(self, AnalysisWindow):
        _translate = QtCore.QCoreApplication.translate
        AnalysisWindow.setWindowTitle(_translate("AnalysisWindow", "AnalysisWindow"))
        self.label5.setText(_translate("AnalysisWindow", "and"))
        self.label6.setText(_translate("AnalysisWindow", "Apprioximate length between the two genes:"))
        self.label3.setText(_translate("AnalysisWindow", "Enter two genes (bases sequences) to analyse the gene between them"))
        self.label.setText(_translate("AnalysisWindow", "Between"))
        self.CorrectButton.setText(_translate("AnalysisWindow", "Analyse"))
        self.textEdit3.setHtml(_translate("AnalysisWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Sequence1</p></body></html>"))
        self.heading.setText(_translate("AnalysisWindow", "Gene Analysis"))
        self.textEdit4.setHtml(_translate("AnalysisWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Sequence2</p></body></html>"))
        self.textEdit.setHtml(_translate("AnalysisWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Results</p></body></html>"))
        self.GoBack.setText(_translate("AnalysisWindow", "Go back"))
        self.DataSetButton.setText(_translate("AnalysisWindow", "Choose a dataset"))


    def openDialogBox(self):
        filename = QFileDialog.getOpenFileName()
        path = filename[0]
        self.textEdit_2.setText(str(path))


    def Analyse(self, string1, string2, approxlength=None):
        if self.textEdit_2.toPlainText() == "":
                self.MessageBoxDirectoryError()
        elif self.textEdit3.toPlainText()=="" or self.textEdit3.toPlainText()=="Sequence1" or self.textEdit4.toPlainText()=="" or self.textEdit4.toPlainText()=="Sequence2" or ((self.textEdit3.toPlainText()=="" and self.textEdit4.toPlainText()=="")) or ((self.textEdit3.toPlainText()=="Sequence1" and self.textEdit4.toPlainText()=="Sequence2")):
                self.MessageBoxGeneError()
        else:
                self.Imp = Implementation(self.textEdit_2.toPlainText())
                self.textEdit.setText(str(self.Imp.gene_analysis(string1, string2, approxlength)))

    def al(self):
        try:
            self.Analyse(self.textEdit3.toPlainText(), self.textEdit4.toPlainText(), int(self.textEdit5.toPlainText()))
        except:
            self.Analyse(self.textEdit3.toPlainText(), self.textEdit4.toPlainText())


    def MessageBoxDirectoryError(self):
        msg = QMessageBox()
        msg.setText("Please choose a data set!")
        msg.setWindowTitle("Error!")
        msg.setIcon(QMessageBox.Critical)
        msg.setStyleSheet("background-color: rgb(0, 0, 0); color: rgb(255, 255, 255)")
        msg.exec_()

    def MessageBoxGeneError(self):
        msg = QMessageBox()
        msg.setText("Cannot proceed until DNA sequence given!")
        msg.setWindowTitle("Error!")
        msg.setIcon(QMessageBox.Critical)
        msg.setStyleSheet("background-color: rgb(0, 0, 0); color: rgb(255, 255, 255)")
        msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnalysisWindow = QtWidgets.QMainWindow()
    ui = Ui_AnalysisWindow()
    ui.setupUi(AnalysisWindow)
    AnalysisWindow.show()
    sys.exit(app.exec_())
